### PR TITLE
Remove dependency on collective.z3cform.widgets

### LINKED ISSUE #107: Remove dependency on collective.z3cform.widgets
That package is not needed in Plone 5; we should move the widget inside collective.polls instead.

### PR DESCRIPTION
**Pull request by hvelarde**
closes #107

### CODE REVIEW

**Comment by hvelarde** [comment]
@rodfersou @puittenbroek I was able to recover a very old branch started by @sneridagh years ago.

I don't know if it works, but at least is a good starting point.

**Comment by puittenbroek** [comment]
All tests are passing, so very good start it seems ;)
Would the test case you made also work excactly the same on the c.z.widgets variant? Just wondering.
Anything we might be missing that isn't covered in tests? Robot test cover the add/remove options the widget does.

I'll check it out locally tomorrow when at work again but looks fine so far 👍

**Comment by hvelarde** [comment]
I just added the CSS and JS linters and there are some issues with the code that we probably want to fix before merging.

I think @rodfersou will like to work with Webpack also.

**Comment by hvelarde** [comment]
I need to review the other tests first.

**Comment by hvelarde** [comment]
@idgserpro FYI

**Comment by hvelarde** [comment]
@puittenbroek do you need a new release?

**Comment by puittenbroek** [comment]
@hvelarde That would be nice yes :) Not urgently .. but somewhere upcoming weeks would be useful. Helps reduce the stack and resolve conflict I had with collective.z3cform.widget :)

**Comment by hvelarde** [comment]
done! https://pypi.python.org/pypi/collective.polls/1.10b1

**Comment by idgserpro** [comment]
Somehow this entered in out spam section. Weird.

Won't we have problems for production installations that have collective.polls before 1.10b1 since collective.z3cform.widgets register a browserlayer and it's not available anymore? https://github.com/collective/collective.z3cform.widgets/blob/34e2d2550c086b6b9a7aeaef8e959baf1debd669/src/collective/z3cform/widgets/profiles/default/browserlayer.xml

**Comment by hvelarde** [comment]
collective.z3cform.widgets is still installed after upgrading; you have to manually uninstall it in case you are not using i; that's documented already in the README file.

**Pull request merged**
