### PR TITLE
Update German translation.

### PR DESCRIPTION
**Pull request by mbaechtold**

### CODE REVIEW

**Comment by mbaechtold** [comment]
Thanks for merging this, @hvelarde. Any estimate on the release 1.6.2?

**Comment by hvelarde** [comment]
I'm having problems running the tests on CI and I need to fix that first; if you can help me we can speed up the process.

also, we need to fix #83.

**Comment by hvelarde** [comment]
done! https://pypi.python.org/pypi/collective.polls/1.6.2

**Comment by mbaechtold** [comment]
Cool. Thank you very much!

**Pull request merged**
