### PR TITLE
Issue 89 - Remove hard dependency on five.grok

### LINKED ISSUE #89: Remove dependency on five.grok

### PR DESCRIPTION
**Pull request by rodfersou**
closes #89

Task still in progress

### CODE REVIEW

**Comment by puittenbroek** [comment]
@rodfersou Are you still working on this?

**Comment by hvelarde** [comment]
@puittenbroek yes, but we've been busy with other stuff; can you help?

**Comment by puittenbroek** [comment]
@hvelarde I'll see what I can do! There aren't that many grok elements

**Comment by puittenbroek** [comment]
Having some problems getting codeanalysis working locally. Working on it :)

**Comment by puittenbroek** [comment]
Travis issue seem related to failing Firefox.. :(

**Comment by hvelarde** [comment]
I have no idea what's going on; we'll need to debug.

**Comment by hvelarde** [comment]
@puittenbroek we're facing the same issue in other packages and I have various PR waiting for a fix.

**Comment by hvelarde** [comment]
@puittenbroek seems we still have some RF tests failing in Plone 4.3 probably because of an issue in lastest release.

**Comment by hvelarde** [comment]
@puittenbroek I finally was able to ran the tests locally and I can confirm we have 3 tests failing.

we're currently working on a customer project and we're not going to be able to take a look on this until next week, probably; feel free to dig further if you can.

**Comment by hvelarde** [comment]
@rodfersou we're not going to be able to completely remove dependency on five.grok until we remove dependency on collective.z3cform.widgets.

I'm going to add a new issue for that.

**Comment by puittenbroek** [comment]
@hvelarde I'll see if I can get robot test running locally, usually my laptop (ubuntu) disagrees :)

**Comment by hvelarde** [comment]
@puittenbroek annotate is there to solve those questions: https://travis-ci.org/collective/collective.polls/jobs/218242509#L938

this is what I did locally:

* download Firefox 45.8.0 ESR
* extract it in `/opt/firefox`
* run tests with `PATH=/opt/firefox:$PATH bin/test`

instead of running tests, I suggest you to try to do manually what the test is trying to achieve; these are the tests that are failing:

* anonymous user should not be able to vote on a poll published on a private folder
* poll tile fails rising an exception

you should run buildout with something like `bin/buildout buildout:test-eggs=collective.cover[tests]` in order to be able to tests all features.

**Comment by puittenbroek** [comment]
@hvelarde Yes, thanks I'll try the firefox thing later if I have time :) For now I fixed the two issues. 
Test are failing in 4.3 due to buildout not yielding the `test` part. 
I've had this in other projects as well, strange thing is that the 4.2 IS working properly.
Do any other builds fail on this? Seem related to the `buildout.plonetest` changes?

**Comment by hvelarde** [comment]
@puittenbroek I made some refactor and I think I'm going to leave the utility with the old name as that's a breaking change and I would have to release as 2.0; the whole utility is somehow useless, IMO, but then we need to do a deeper refactor.

I working on fixing an issue in collective.cover that is breaking the tests here.

**Comment by puittenbroek** [comment]
Okay, yeah I found the utility name confusing. Especially in combination with the content class having the same naming and same interface name :)

**Comment by hvelarde** [comment]
IMO, there are many things in this package that are overcomplicated and I dislike that; you know, when people discover the hammer they want to hit nails everywhere ;-)

**Pull request merged**
